
// Bun's Peg example
// << >>, # are an extended constructor
// see www.libbun.org/peg

import Value from value.peg;

TopLevel
  = Expr
  ;

_ = [ \t\n]+;

Expr
  = '(' _? << Predicate (Expr@)? (_ Expr@)* >> ')'
  / Value
  ;

Predicate
  = '+'  _+ #add
  / '-'  _+ #sub
  / '*'  _+ #mul
  / '/'  _+ #div
  / '%'  _+ #mod
  / '<'  _+ #lt
  / '<=' _+ #lte
  / '>'  _+ #gt
  / '>=' _+ #gte
  / '==' _+ #eq
  / '!=' _+ #neq
  ;

