// ctype.peg
// these types are defined mainly for minic.peg


import _ from spacing.peg;

BasicType
 = 'void'     #Tvoid
 / 'boolean'  #Tboolean
 / 'char'     #Tint8
 / 'short'    #Tint16
 / 'int'      #Tint
 / 'long'     #Tint64
 / 'float'    #Tfloat
 / 'double'   #Tdouble
 ;

Type
 = << BasicType >>
 / 'struct' _ << [A-Za-z_][A-Za-z0-9_]* #type >>
 / Type <<@ '*' #pointer >>
 ;

TopLevel
 = Type
 ;

